'use client';

import Image from 'next/image';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import type { Dict, Locale } from '@/lib/i18n';
import qrImage from '@/public/shamcash-venus-qr.jpeg';
import englishCover from '@/public/conscious-diplomacy-en-cover.jpg';
import arabicCover from '@/public/conscious-diplomacy-ar-cover.jpg';
import styles from './page.module.css';

interface Props {
  lang: Locale;
  d: Dict;
}

type CheckoutStatus = 'idle' | 'checking' | 'approved' | 'rejected' | 'error';

interface VerificationResponse {
  approved: boolean;
  reasonCode?: string;
  message?: string;
  readUrl?: string;
  downloadUrl?: string;
  expiresIn?: number;
  receipt?: {
    transactionNumber?: string;
    amount?: number;
    currency?: string;
    recipientName?: string;
    transactionDate?: string;
  };
}

const SHAM_CASH_ADDRESS = '6ee6937181709f3f0b3b2e6adb0b415c';
const MAX_FILE_BYTES = 10 * 1024 * 1024;

const copy = {
  en: {
    eyebrow: 'The digital edition',
    title: 'Conscious Diplomacy',
    intro: 'Choose your edition, pay $2.99, $3.00 or $3.10 through Sham Cash, then upload the receipt. Private server-side OCR checks the payment fields and unlocks an approved purchase immediately.',
    choose: '01 — Choose your edition',
    english: 'English edition',
    arabic: 'Arabic edition',
    pages: 'pages',
    payment: '02 — Make the payment',
    scan: 'Scan in Sham Cash',
    amount: 'Amount',
    recipient: 'Recipient',
    address: 'Account address',
    copy: 'Copy',
    copied: 'Copied',
    exact: 'Send $2.99, $3.00 or $3.10 USD. Keep the original receipt generated by Sham Cash after the transfer.',
    receipt: '03 — Upload your receipt',
    automatic: 'Private OCR check',
    upload: 'Choose a receipt image or PDF',
    formats: 'JPG, PNG, WEBP or PDF · maximum 10 MB',
    replace: 'Choose a different file',
    confirm: 'I confirm that I made this payment to Venus Alarbeed and that this receipt has not been used before.',
    submit: 'Verify receipt & unlock book',
    checking: ['Reading the receipt with OCR…', 'Checking the payment fields…', 'Creating your private book link…'],
    approved: 'Payment approved',
    ready: 'Your private download is ready. The link expires shortly, so save the book now.',
    read: 'Read in browser',
    download: 'Download PDF',
    rejected: 'Receipt not approved',
    retry: 'Try another receipt',
    privacy: 'No AI service and no database are used. The receipt is read by OCR on the private checkout server, held only in memory during the check, and then discarded.',
    config: 'Automatic verification is not connected yet. Add the verification endpoint during deployment.',
    invalidFile: 'Please upload a JPG, PNG, WEBP or PDF smaller than 10 MB.',
    failed: 'We could not verify this receipt. Please check the file and try again.',
  },
  ar: {
    eyebrow: 'النسخة الرقمية',
    title: 'الدبلوماسية الواعية',
    intro: 'اختر نسختك، ادفع 2.99 أو 3 أو 3.10 دولارات عبر شام كاش، ثم ارفع الإيصال. يقرأ الخادم الخاص بيانات الدفع عبر OCR وتُفتح النسخة المقبولة مباشرة.',
    choose: '01 — اختر نسختك',
    english: 'النسخة الإنجليزية',
    arabic: 'النسخة العربية',
    pages: 'صفحة',
    payment: '02 — أرسل المبلغ',
    scan: 'امسح الرمز في شام كاش',
    amount: 'المبلغ',
    recipient: 'المستلم',
    address: 'عنوان الحساب',
    copy: 'نسخ',
    copied: 'تم النسخ',
    exact: 'أرسل 2.99 أو 3 أو 3.10 دولارات أمريكية واحتفظ بالإيصال الأصلي الذي ينشئه شام كاش بعد التحويل.',
    receipt: '03 — ارفع إيصالك',
    automatic: 'فحص OCR خاص',
    upload: 'اختر صورة الإيصال أو ملف PDF',
    formats: 'JPG أو PNG أو WEBP أو PDF · بحد أقصى 10 ميغابايت',
    replace: 'اختر ملفاً آخر',
    confirm: 'أؤكد أنني أجريت هذا الدفع إلى فينوس العربيد وأن هذا الإيصال لم يُستخدم من قبل.',
    submit: 'تحقق من الإيصال وافتح الكتاب',
    checking: ['جارٍ قراءة الإيصال عبر OCR…', 'جارٍ التحقق من بيانات الدفع…', 'جارٍ إنشاء رابط الكتاب الخاص…'],
    approved: 'تم قبول الدفع',
    ready: 'نسختك الخاصة جاهزة. تنتهي صلاحية الرابط قريباً، لذا احفظ الكتاب الآن.',
    read: 'قراءة في المتصفح',
    download: 'تنزيل PDF',
    rejected: 'لم يتم قبول الإيصال',
    retry: 'جرّب إيصالاً آخر',
    privacy: 'لا نستخدم خدمة ذكاء اصطناعي ولا قاعدة بيانات. يقرأ خادم الدفع الخاص الإيصال عبر OCR في الذاكرة فقط ثم يتخلص منه بعد الفحص.',
    config: 'لم يتم ربط خدمة التحقق التلقائي بعد. أضف رابط الخدمة عند النشر.',
    invalidFile: 'يرجى رفع JPG أو PNG أو WEBP أو PDF بحجم أقل من 10 ميغابايت.',
    failed: 'تعذر التحقق من هذا الإيصال. تحقق من الملف وحاول مرة أخرى.',
  },
} as const;

export default function BookCheckout({ lang, d }: Props) {
  const t = copy[lang];
  const [edition, setEdition] = useState<Locale>(lang);
  const [receipt, setReceipt] = useState<File | null>(null);
  const [status, setStatus] = useState<CheckoutStatus>('idle');
  const [message, setMessage] = useState('');
  const [result, setResult] = useState<VerificationResponse | null>(null);
  const [checkingStep, setCheckingStep] = useState(0);
  const [copied, setCopied] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (status !== 'checking') return;

    const timer = window.setInterval(() => {
      setCheckingStep((current) => (current + 1) % t.checking.length);
    }, 1800);

    return () => window.clearInterval(timer);
  }, [status, t.checking.length]);

  const validateFile = (file: File) => {
    const allowed = ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'];
    return allowed.includes(file.type) && file.size > 0 && file.size <= MAX_FILE_BYTES;
  };

  const selectFile = (file: File | undefined) => {
    setResult(null);
    setMessage('');
    setStatus('idle');

    if (!file || !validateFile(file)) {
      setReceipt(null);
      setMessage(t.invalidFile);
      return;
    }

    setReceipt(file);
  };

  const copyAddress = async () => {
    await navigator.clipboard.writeText(SHAM_CASH_ADDRESS);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1800);
  };

  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (!receipt || !validateFile(receipt)) {
      setMessage(t.invalidFile);
      return;
    }

    const endpoint = process.env.NEXT_PUBLIC_RECEIPT_VERIFY_URL;
    if (!endpoint) {
      setStatus('error');
      setMessage(t.config);
      return;
    }

    const form = new FormData(event.currentTarget);
    form.set('receipt', receipt);
    form.set('bookLanguage', edition);
    form.set('uiLanguage', lang);

    setStatus('checking');
    setCheckingStep(0);
    setMessage('');
    setResult(null);

    try {
      const response = await fetch(endpoint, { method: 'POST', body: form });
      const payload = (await response.json()) as VerificationResponse;

      setResult(payload);
      setMessage(payload.message ?? (payload.approved ? t.ready : t.failed));
      setStatus(payload.approved && payload.downloadUrl ? 'approved' : 'rejected');
    } catch {
      setStatus('error');
      setMessage(t.failed);
    }
  };

  const reset = () => {
    setReceipt(null);
    setResult(null);
    setMessage('');
    setStatus('idle');
    if (fileRef.current) fileRef.current.value = '';
  };

  const editions = [
    { id: 'en' as const, label: t.english, pages: 261, cover: englishCover },
    { id: 'ar' as const, label: t.arabic, pages: 258, cover: arabicCover },
  ];

  return (
    <div className={styles.page}>
      <header className={styles.hero}>
        <div className={`container ${styles.heroInner}`}>
          <div className={styles.eyebrow}><span />{t.eyebrow}</div>
          <h1>{t.title}</h1>
          <p>{t.intro}</p>
          <div className={styles.price}><span>$</span>2.99 <small>USD</small></div>
        </div>
      </header>

      <form className={`container ${styles.checkout}`} onSubmit={submit}>
        <section className={styles.section} aria-labelledby="edition-heading">
          <div className={styles.sectionHeading}>
            <h2 id="edition-heading">{t.choose}</h2>
            <span>{edition.toUpperCase()}</span>
          </div>
          <div className={styles.editions}>
            {editions.map((item) => (
              <label key={item.id} className={`${styles.edition} ${edition === item.id ? styles.editionSelected : ''}`}>
                <input
                  type="radio"
                  name="edition"
                  value={item.id}
                  checked={edition === item.id}
                  onChange={() => setEdition(item.id)}
                />
                <Image src={item.cover} alt="" className={styles.cover} sizes="(max-width: 600px) 38vw, 150px" />
                <span className={styles.editionCopy}>
                  <strong>{item.label}</strong>
                  <small>{item.pages} {t.pages} · PDF</small>
                </span>
                <span className={styles.selectionMark} aria-hidden="true" />
              </label>
            ))}
          </div>
        </section>

        <section className={styles.section} aria-labelledby="payment-heading">
          <div className={styles.sectionHeading}>
            <h2 id="payment-heading">{t.payment}</h2>
            <span>SHAM CASH</span>
          </div>
          <div className={styles.paymentGrid}>
            <div className={styles.qrPanel}>
              <Image src={qrImage} alt={lang === 'ar' ? 'رمز شام كاش الخاص بفينوس العربيد' : 'Venus Alarbeed Sham Cash payment QR'} priority />
              <p>{t.scan}</p>
            </div>
            <div className={styles.paymentDetails}>
              <dl>
                <div><dt>{t.amount}</dt><dd>$2.99 / $3.00 / $3.10 USD</dd></div>
                <div><dt>{t.recipient}</dt><dd>{d.hero.nameFirst} {d.hero.nameLast}</dd></div>
                <div className={styles.addressRow}>
                  <dt>{t.address}</dt>
                  <dd><code>{SHAM_CASH_ADDRESS}</code><button type="button" onClick={copyAddress}>{copied ? t.copied : t.copy}</button></dd>
                </div>
              </dl>
              <p className={styles.exactNote}>{t.exact}</p>
            </div>
          </div>
        </section>

        <section className={styles.section} aria-labelledby="receipt-heading">
          <div className={styles.sectionHeading}>
            <h2 id="receipt-heading">{t.receipt}</h2>
            <span>{t.automatic}</span>
          </div>

          <label className={`${styles.upload} ${receipt ? styles.uploadReady : ''}`}>
            <input
              ref={fileRef}
              type="file"
              name="receipt"
              accept="image/jpeg,image/png,image/webp,application/pdf,.jpg,.jpeg,.png,.webp,.pdf"
              required
              onChange={(event) => selectFile(event.target.files?.[0])}
            />
            <span className={styles.uploadIcon} aria-hidden="true">
              {receipt ? '✓' : '↑'}
            </span>
            <strong>{receipt?.name ?? t.upload}</strong>
            <small>{receipt ? `${(receipt.size / 1024 / 1024).toFixed(2)} MB · ${t.replace}` : t.formats}</small>
          </label>

          <label className={styles.confirmation}>
            <input name="confirmation" type="checkbox" required />
            <span>{t.confirm}</span>
          </label>

          {message && status !== 'approved' && (
            <div className={`${styles.notice} ${status === 'rejected' || status === 'error' ? styles.noticeError : ''}`} role="alert">
              {message}
            </div>
          )}

          {status === 'checking' ? (
            <div className={styles.checking} aria-live="polite">
              <span className={styles.spinner} />
              <strong>{t.checking[checkingStep]}</strong>
              <div><span style={{ width: `${34 + checkingStep * 30}%` }} /></div>
            </div>
          ) : status === 'approved' && result?.downloadUrl ? (
            <div className={styles.approved} role="status">
              <span className={styles.approvedMark}>✓</span>
              <div>
                <h3>{t.approved}</h3>
                <p>{message || t.ready}</p>
                {result.receipt?.transactionNumber && <small>#{result.receipt.transactionNumber}</small>}
              </div>
              <div className={styles.approvedActions}>
                {result.readUrl && <a className="btn btn-ghost-light" href={result.readUrl} target="_blank" rel="noreferrer">{t.read} ↗</a>}
                <a className="btn btn-ghost-light" href={result.downloadUrl}>{t.download} ↓</a>
              </div>
            </div>
          ) : (
            <div className={styles.submitRow}>
              <button className={`btn ${styles.submit}`} type="submit">{t.submit} →</button>
              {(status === 'rejected' || status === 'error') && (
                <button className={styles.retry} type="button" onClick={reset}>{t.retry}</button>
              )}
            </div>
          )}

          <p className={styles.privacy}>{t.privacy}</p>
        </section>
      </form>
    </div>
  );
}
